#spring:
#  datasource:
#    username: root
#    password: 1234
#    url: jdbc:mysql://localhost:3306/springGame
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    proper